### PR TITLE
Add option to support illegal keys

### PR DESCRIPTION
**Pull request by pvillard31**

### CODE REVIEW

**Review by trixpan — APPROVED** [review]
lgtm

**Comment by trixpan** [comment]
@pvillard31 thanks for that. Will try to release sometimes later today

**Comment by pvillard31** [comment]
Wow, awesome :) thanks @trixpan !

**Comment by pvillard31** [comment]
Hey @trixpan - absolutely no rush here but let me know if you need something from me for a release. Have a very good WE!

**Pull request merged**
