### PR TITLE
Upgrade Dependencies for Jakarta EE 10

### PR DESCRIPTION
**Pull request by exceptionfactory**
This pull request upgrades all project dependencies to the latest versions, aligning with the requirements of [Jakarta EE 10](https://jakarta.ee/release/10/).

These upgrades should be considered a breaking change for the project version.

Jakarta EE 10 includes the Jakarta Validation API version 3, which is the primary motivation for upgrading dependencies. Jakarta EE 10 also requires Java 11 as the minimum version, so this pull request updates plugins and workflows to build with Java 11.

Additional changes include adding JavaDoc comments in several places to resolve JavaDoc plugin warnings.

These upgrades also align with Jakarta EE 10 support for Apache NiFi 2.0.

Here is the complete list of upgraded dependencies and plugins:

- Upgraded Validation API from 1.1.0 to 3.0.2
- Upgraded SLF4J from 1.7.30 to 2.0.9
- Upgraded JUnit from 4.13.1 to 5.10.1
- Upgraded Hibernate Validator from 5.4.3 to 8.0.1
- Upgraded Expression Language from 3.0.1 to 5.0.0-M1
- Upgraded Maven JAR Plugin from 2.3.2 to 3.3.0
- Upgraded Maven Source Plugin from 2.1.2 to 3.3.0
- Upgraded Maven JavaDoc Plugin from 2.10.4 to 3.6.3
- Upgraded Maven Compiler Plugin from 3.8.1 to 3.12.1
- Upgraded Maven Checkstyle Plugin from 3.1.2 to 3.3.1
- Upgraded Maven GPG Plugin from 3.0.1 to 3.1.0
- Upgraded Apache Rat Plugin from 0.13 to 0.15

### CODE REVIEW

**Comment by trixpan** [comment]
@exceptionfactory incredible work, thanks. I will cut a new major release sometime later this week.

**Comment by exceptionfactory** [comment]
> @exceptionfactory incredible work, thanks. I will cut a new major release sometime later this week.

Thanks @trixpan, I appreciate the feedback and response!

**Comment by exceptionfactory** [comment]
@trixpan Just following up on this, let me know if you have any questions before proceeding. Thanks!

**Comment by trixpan** [comment]
> @trixpan Just following up on this, let me know if you have any questions before proceeding. Thanks!

Hi David, apologies for the delay. I hope to solve this asap

**Pull request merged**
