### PR TITLE
ISSUE-8 do not compile a the same regex twice for each header processed

### PR DESCRIPTION
**Pull request by ottobackwards**
Use a static member instead.

### CODE REVIEW

**Comment by ottobackwards** [comment]
note:  this PR has the fix for ISSUE-6 in it.  When(?) that issue lands, I'll rebase.

**Comment by ottobackwards** [comment]
@trixpan ping

**Comment by trixpan** [comment]
@ottobackwards apologies for the delay. Can you rebase? 

Cheers

**Comment by ottobackwards** [comment]
all set

**Pull request merged**
